# Generated by Django 5.0.7 on 2024-07-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_unit_unit_hrs_term_unit_unit_hrs_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='unit_hrs_term',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='unit_hrs_week',
        ),
        migrations.AddField(
            model_name='unit',
            name='teaching_hrs_term',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='teaching_hrs_week',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
