# Generated by Django 5.0.7 on 2024-07-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_department_is_admission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='teaching_hrs_per_class',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
